name: Tests and Linters
on: 
  workflow_dispatch:
  push:
    branches:
      - "cicd"
jobs:
  setup_environment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --no-root
        
      - name: Poetry config installer.max-workers
        run: poetry config installer.max-workers 10

      - name: Check Python version
        run: python --version
            
      - name: Check Poetry version
        run: poetry --version

      - name: Poetry check configs
        run: poetry config --list

  test:
    runs-on: ubuntu-22.04
    needs: setup_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --no-root

      - name: Print number of tests
        run: echo There are no tests!

  snakemake:
    runs-on: ubuntu-22.04
    needs: setup_environment
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --no-root

      - name: Print Snakemake version
        run: poetry run snakemake --lint

  flake:
    runs-on: ubuntu-22.04
    needs: setup_environment
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --no-root

      - name: Check Python modules
        run: poetry run flake8 ./comp_ds_prj/

      - name: Check Jupyter Notebooks
        run: poetry run nbqa flake8 ./notebooks/

  pydocstyle:
    runs-on: ubuntu-22.04
    needs: setup_environment
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --no-root

      - name: Check Python modules
        run: poetry run pydocstyle --match='(?!test_|__init__).*\.py' ./comp_ds_prj/

      - name: Check Jupyter Notebooks
        run: poetry run pydocstyle --match='(?!test_|__init__).*\.ipynb' ./notebooks/