name: Tests and Linters
on: 
  workflow_dispatch:
  push:
    branches-ignore:
      - docs
  pull_request:
    branches:
      - main
env:
  POETRY_INSTALLER_MAX_WORKERS: 10
  GDRIVE_CREDENTIALS_DATA: ${{ secrets.DVC_GDRIVE_SECRET }}
jobs:
  check_environment:
    runs-on: [self-hosted,ubuntu,ds,no-gpu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check Python version
        run: python --version
            
      - name: Check Poetry version
        run: poetry --version

      - name: Poetry check configs
        run: poetry config --list

      - name: Check DVC version
        run: |
          echo DVC version: 
          poetry run dvc --version

  autoformatter:
    runs-on: [self-hosted,ubuntu,ds,no-gpu]
    needs: check_environment
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: poetry install

      - name: isort Python modules
        run: poetry run isort ./comp_ds_prj/

      - name: isort Jupyter Notebooks
        run: poetry run nbqa isort ./notebooks/

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Automated Change - sort imports
            
  test:
    runs-on: [self-hosted,ubuntu,ds,no-gpu]
    needs: [check_environment, autoformatter]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: poetry install

      - name: Pull data
        run: poetry run dvc pull

      - name: Print number of tests
        run: echo There are no tests!

  flake:
    runs-on: [self-hosted,ubuntu,ds,no-gpu]
    needs: [check_environment, autoformatter]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: poetry install

      - name: Check Python modules
        run: poetry run flake8 ./comp_ds_prj/

      - name: Check Jupyter Notebooks
        run: poetry run nbqa flake8 ./notebooks/

  pydocstyle:
    runs-on: [self-hosted,ubuntu,ds,no-gpu]
    needs: [check_environment, autoformatter]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: poetry install

      - name: Check Python modules
        run: poetry run pydocstyle --match='(?!test_|__init__).*\.py' ./comp_ds_prj/

      - name: Check Jupyter Notebooks
        run: poetry run nbqa pydocstyle --match='(?!test_|__init__).*\.ipynb' ./notebooks/

  mypy:
    runs-on: [self-hosted,ubuntu,ds,no-gpu]
    needs: [check_environment, autoformatter]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: poetry install

      - name: Check Python modules
        run: poetry run mypy ./comp_ds_prj/

      - name: Check Jupyter Notebooks
        run: poetry run nbqa mypy ./notebooks/
